# Generated by Django 4.1.1 on 2025-01-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0005_auto_20250131_1531"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoriamanutencao",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="servico",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="servicoadicional",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
