# Generated by Django 4.1.1 on 2026-03-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0006_alter_categoriamanutencao_id_alter_servico_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servico",
            old_name="protocole",
            new_name="protocolo",
        ),
        migrations.AlterField(
            model_name="categoriamanutencao",
            name="titulo",
            field=models.CharField(
                choices=[
                    ("TVM", "Trocar válcula do motor"),
                    ("TO", "Troca de óleo"),
                    ("B", "Balanceamento"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="servico",
            name="data_entrega",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="servico",
            name="data_inicio",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="servico",
            name="servicos_adicionais",
            field=models.ManyToManyField(blank=True, to="servicos.servicoadicional"),
        ),
        migrations.AlterField(
            model_name="servicoadicional",
            name="preco",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
