# Generated by Django 4.1.1 on 2026-03-24 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0005_remove_carro_consertos_remove_carro_lavagens_and_more"),
        ("servicos", "0007_rename_protocole_servico_protocolo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adicional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, verbose_name="Nome")),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Preço (R$)"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Adicional",
                "verbose_name_plural": "Adicionais",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Estetica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("polimento", "Polimento"),
                            ("vitrificacao", "Vitrificação"),
                            ("higienizacao", "Higienização Interna"),
                            ("cristalizacao", "Cristalização"),
                            ("peliculas", "Películas"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
                ("data", models.DateTimeField(auto_now_add=True, verbose_name="Data")),
                (
                    "carro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="esteticas",
                        to="clientes.carro",
                        verbose_name="Carro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estética",
                "verbose_name_plural": "Estéticas",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Lavagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("simples", "Simples"),
                            ("completa", "Completa"),
                            ("motorista", "A Pedido do Motorista"),
                        ],
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Valor (R$)"
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
                ("data", models.DateTimeField(auto_now_add=True, verbose_name="Data")),
                (
                    "carro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lavagens",
                        to="clientes.carro",
                        verbose_name="Carro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lavagem",
                "verbose_name_plural": "Lavagens",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="OrdemServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aguardando", "Aguardando"),
                            ("em_andamento", "Em andamento"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="aguardando",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=8,
                        verbose_name="Total (R$)",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data"),
                ),
                (
                    "adicionais",
                    models.ManyToManyField(
                        blank=True, to="servicos.adicional", verbose_name="Adicionais"
                    ),
                ),
                (
                    "carro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens",
                        to="clientes.carro",
                        verbose_name="Carro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem de Serviço",
                "verbose_name_plural": "Ordens de Serviço",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ServicoBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome do Serviço"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[("lavagem", "Lavagem"), ("estetica", "Estética")],
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "descricao",
                    models.TextField(blank=True, verbose_name="Itens incluídos"),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Preço (R$)"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Serviço",
                "verbose_name_plural": "Serviços",
                "ordering": ["categoria", "nome"],
            },
        ),
        migrations.RemoveField(
            model_name="servico",
            name="categoria_manutencao",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="cliente",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="servicos_adicionais",
        ),
        migrations.DeleteModel(
            name="CategoriaManutencao",
        ),
        migrations.DeleteModel(
            name="Servico",
        ),
        migrations.DeleteModel(
            name="ServicoAdicional",
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="servico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="servicos.servicobase",
                verbose_name="Serviço",
            ),
        ),
    ]
