# Generated by Django 4.1.1 on 2026-04-03 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0006_carro_cor_carro_modelo_carro_tipo_alter_carro_ano_and_more"),
        (
            "servicos",
            "0008_adicional_estetica_lavagem_ordemservico_servicobase_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaVeiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "descricao",
                    models.TextField(
                        blank=True, null=True, verbose_name="Exemplos de carros"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de Veículo",
                "verbose_name_plural": "Categorias de Veículo",
            },
        ),
        migrations.CreateModel(
            name="TabelaPreco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Preço (R$)"
                    ),
                ),
                (
                    "categoria_veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="servicos.categoriaveiculo",
                        verbose_name="Categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tabela de Preço",
                "verbose_name_plural": "Tabela de Preços",
            },
        ),
        migrations.CreateModel(
            name="TipoServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "descricao",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Tipo de Serviço",
                "verbose_name_plural": "Tipos de Serviço",
            },
        ),
        migrations.RemoveField(
            model_name="estetica",
            name="carro",
        ),
        migrations.RemoveField(
            model_name="lavagem",
            name="carro",
        ),
        migrations.AlterModelOptions(
            name="ordemservico",
            options={
                "ordering": ["-data"],
                "verbose_name": "Ordem de Serviço",
                "verbose_name_plural": "Ordens de Serviço",
            },
        ),
        migrations.RenameField(
            model_name="ordemservico",
            old_name="criado_em",
            new_name="data",
        ),
        migrations.RemoveField(
            model_name="ordemservico",
            name="adicionais",
        ),
        migrations.RemoveField(
            model_name="ordemservico",
            name="servico",
        ),
        migrations.RemoveField(
            model_name="ordemservico",
            name="total",
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="preco",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="Preço (R$)"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="carro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordens",
                to="clientes.carro",
                verbose_name="Carro",
            ),
        ),
        migrations.AlterField(
            model_name="ordemservico",
            name="status",
            field=models.CharField(
                choices=[
                    ("aguardando", "Aguardando"),
                    ("em_andamento", "Em Andamento"),
                    ("finalizado", "Finalizado"),
                ],
                default="aguardando",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.DeleteModel(
            name="Adicional",
        ),
        migrations.DeleteModel(
            name="Estetica",
        ),
        migrations.DeleteModel(
            name="Lavagem",
        ),
        migrations.DeleteModel(
            name="ServicoBase",
        ),
        migrations.AddField(
            model_name="tabelapreco",
            name="tipo_servico",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="servicos.tiposervico",
                verbose_name="Serviço",
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="tipo_servico",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="servicos.tiposervico",
                verbose_name="Serviço",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="tabelapreco",
            unique_together={("tipo_servico", "categoria_veiculo")},
        ),
    ]
