# Generated by Django 4.1.1 on 2026-04-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servicos", "0009_categoriaveiculo_tabelapreco_tiposervico_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adicional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Preço (R$)"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Adicional",
                "verbose_name_plural": "Adicionais",
            },
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="adicionais",
            field=models.ManyToManyField(
                blank=True, to="servicos.adicional", verbose_name="Adicionais"
            ),
        ),
    ]
