# Generated by Django 4.1.1 on 2025-02-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_alter_carro_id_alter_cliente_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
