# Generated by Django 4.1.1 on 2026-03-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0005_remove_carro_consertos_remove_carro_lavagens_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="carro",
            name="cor",
            field=models.CharField(
                blank=True,
                choices=[
                    ("preto", "Preto"),
                    ("branco", "Branco"),
                    ("prata", "Prata"),
                    ("cinza", "Cinza"),
                    ("vermelho", "Vermelho"),
                    ("azul", "Azul"),
                    ("verde", "Verde"),
                    ("amarelo", "Amarelo"),
                    ("outro", "Outro"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="carro",
            name="modelo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="carro",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hatch", "Hatch"),
                    ("sedan", "Sedan"),
                    ("suv", "SUV"),
                    ("caminhonete", "Caminhonete"),
                    ("moto", "Moto"),
                    ("van", "Van"),
                    ("pickup", "Pickup"),
                    ("esportivo", "Esportivo"),
                    ("outro", "Outro"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="carro",
            name="ano",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
