# Generated by Django 4.2.29 on 2026-04-14 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0006_carro_cor_carro_modelo_carro_tipo_alter_carro_ano_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carro",
            options={
                "ordering": ["carro"],
                "verbose_name": "Carro",
                "verbose_name_plural": "Carros",
            },
        ),
        migrations.AlterModelOptions(
            name="cliente",
            options={
                "ordering": ["nome", "sobrenome"],
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
        migrations.RemoveField(
            model_name="carro",
            name="modelo",
        ),
        migrations.AlterField(
            model_name="carro",
            name="cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carros",
                to="clientes.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="carro",
            name="placa",
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cpf",
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefone",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
